import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Blogging platform',
  description: 'Generated by create next app',
  keywords: 'html, css, javascript, entertainment, food, sports'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <section><Navbar/></section>
        <main className='flex md:flex-row'>{children}</main>
        <Footer className='grid md:grid-row'/>
      </body>
    </html>
  )
}
